# Generated by Django 3.0.6 on 2020-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_url', models.TextField()),
                ('descreption', models.TextField()),
                ('instructions', models.TextField()),
                ('yields', models.TextField()),
                ('cooking_time', models.TextField()),
                ('by', models.TextField()),
                ('tags', models.ManyToManyField(to='recipe.Tag')),
            ],
        ),
    ]
