# Generated by Django 3.0.6 on 2020-05-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingrediet',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.TextField(unique=True),
        ),
    ]
