# Generated by Django 3.0.6 on 2020-05-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200516_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.TextField(unique=True),
        ),
    ]
