# Generated by Django 3.0.6 on 2020-05-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200516_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
