# Generated by Django 3.0.6 on 2020-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20200516_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diettype', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisine',
            field=models.ManyToManyField(to='recipe.Cuisine'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diettype',
            field=models.ManyToManyField(to='recipe.DietType'),
        ),
    ]
