# Generated by Django 3.0.6 on 2020-05-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20200517_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('author', models.TextField()),
                ('show', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='recipe.Category')),
                ('tags', models.ManyToManyField(to='recipe.Tag')),
            ],
        ),
    ]
