# Generated by Django 3.0.6 on 2020-05-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_auto_20200518_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created',
        ),
    ]
