# Generated by Django 3.0.6 on 2020-05-18 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_blogpost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cal',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
