# Generated by Django 3.0.6 on 2020-05-18 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_recipe_cal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
