# Generated by Django 3.0.6 on 2020-05-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_auto_20200518_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='show',
        ),
    ]
