# Generated by Django 3.0.6 on 2020-05-18 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_auto_20200519_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='api_id',
            field=models.TextField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
