# Generated by Django 3.0.6 on 2020-05-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_recipe_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ass_recipe',
            field=models.TextField(blank=True),
        ),
    ]
