# Generated by Django 3.0.6 on 2020-05-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_blogpost_ass_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
