# Generated by Django 3.0.6 on 2020-06-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('comment', models.TextField()),
                ('email', models.ManyToManyField(to='blog.Email')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('meta_descreption', models.TextField(max_length=155)),
                ('feat_img', models.URLField()),
                ('body', models.TextField()),
                ('author', models.TextField()),
                ('date', models.DateField(blank=True)),
                ('time_to_read', models.CharField(max_length=2)),
                ('published', models.BooleanField()),
                ('category', models.ManyToManyField(limit_choices_to=1, to='blog.Category')),
                ('comments', models.ManyToManyField(blank=True, to='blog.Comment')),
                ('keywords', models.ManyToManyField(to='blog.KeyWord')),
            ],
        ),
    ]
