# Generated by Django 3.0.6 on 2020-06-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_auto_20200521_1233'),
        ('blog', '0004_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='recipe',
            field=models.ManyToManyField(blank=True, to='recipe.Recipe'),
        ),
    ]
