# Generated by Django 3.0.6 on 2020-06-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='shares',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
