# Generated by Django 3.0.6 on 2020-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_shares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.TextField(default='ShefHat'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='shares',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
